version: '3.8'

services:
  php-app:
    build: .
    image: joemuldowney/admin-portal:v1  
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}